apiVersion: mxl.qvest-digital.com/v1alpha1
kind: MxlReceiver
metadata:
  name: mxl-video-receiver
  namespace: mxl-csi-test
spec:
  flowID: "5fbec3b1-1b0f-417d-9059-8b94a47197ed"
  provider: "tcp"
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mxl-k8s-video-flow-reader