apiVersion: v1
kind: Pod
metadata:
  name: mxl-producer
  namespace: mxl-test
spec:
  # Pins the pod to the same node as your domain-pv
  nodeSelector:
    kubernetes.io/hostname: mtllppdmh002
  containers:
  - name: producer
    image: ghcr.io/cbcrc/gst-mxl-rs:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      capabilities:
        add:
        - IPC_LOCK
        - SYS_RESOURCE
    volumeMounts:
    # 1. Mount the shared memory PVC
    - name: mxl-domain
      mountPath: /home/mxl/domain
    # 2. Mount the flow configuration
    - name: flow-config
      mountPath: /home/mxl/config
    # 3. Provide the args so the application knows what to run and where
    args: ["/usr/bin/mxl-gst-testsrc -d domain -v config/flow.json"]
  volumes:
  - name: mxl-domain
    persistentVolumeClaim:
      claimName: mxl-domain-pvc
  - name: flow-config
    configMap:
      name: mxl-video-flow-description