nameOverride: ""
fullnameOverride: ""

driver:
  name: mxl.csi.cbcrc.ca
  endpoint: unix:///csi/csi.sock
  sharedHostPath: /run/mxl/domain

image:
  repository: ghcr.io/cbcrc/mxl-csi
  tag: "0.2.6"
  pullPolicy: IfNotPresent

imagePullSecrets: []

controller:
  replicaCount: 1
  nodeID: controller
  nodeSelector: {}
  tolerations: []
  affinity: {}
  serviceAccount:
    create: true
    name: ""
  provisioner:
    image: registry.k8s.io/sig-storage/csi-provisioner
    tag: v5.1.0
    pullPolicy: IfNotPresent
    leaderElection: true
  livenessProbe:
    image: registry.k8s.io/sig-storage/livenessprobe
    tag: v2.15.0
    pullPolicy: IfNotPresent

node:
  hostNetwork: true
  nodeSelector: {}
  tolerations: []
  affinity: {}
  serviceAccount:
    create: true
    name: ""
  registrar:
    image: registry.k8s.io/sig-storage/csi-node-driver-registrar
    tag: v2.13.0
    pullPolicy: IfNotPresent
  livenessProbe:
    image: registry.k8s.io/sig-storage/livenessprobe
    tag: v2.15.0
    pullPolicy: IfNotPresent
    healthPort: 9808

rbac:
  create: true

csiDriver:
  create: true
  attachRequired: false
  podInfoOnMount: false
  fsGroupPolicy: None
  volumeLifecycleModes:
    - Persistent

storageClass:
  create: true
  name: mxl-domain-sc
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
  allowVolumeExpansion: false
